#!/usr/bin/env python
# coding: utf-8

# # M2Pi NRC Swarming ODE Model

# In[1]:


from scipy.integrate import odeint
import numpy as np
import matplotlib.pyplot as plt


# In[36]:


def swarm_model (z,t):
    # params
    q = 3.52*10**(-6)
    m = 1.12*10**(-5)
    eta = 1
    
    # assign each ODE to a vector element
    x = z[0]
    v = z[1]
    
    #define ODEs
    
    dxdt = v
    dvdt = (-np.sign(v)*(q/m)*v**2)-x*(eta/m)
    
    return[dxdt,dvdt]

# initial conditions
z0 = [0,0]

# declare a time vector (time window)
t = np.linspace(0,20,100)
z = odeint(swarm_model,z0,t)

x = z[:,0]
v = z[:,1]

# plot the results

plt.plot(t,z[:,0])
plt.ylabel('velocity (m/s)')
plt.xlabel('time (s)')
#plt.legend(loc='best')
plt.show()

plt.plot(t,z[:,1])
plt.ylabel('position')
plt.xlabel('time (s)')
#plt.legend(loc='best')
plt.show()


# In[40]:


def swarm_model (z,t):
    # params
    q = 3.52*10**(-6)
    m = 1.12*10**(-5)
    eta = 1
    
    # assign each ODE to a vector element
    x = z[0]
    v = z[1]
    
    #define ODEs
    
    dxdt = v
    dvdt = (-np.sign(v)*(q/m)*v**2)-x*(eta/m)
    
    return[dxdt,dvdt]

# initial conditions
z0 = [1,1]

# declare a time vector (time window)
t = np.linspace(0,20,1000)
z = odeint(swarm_model,z0,t)

x = z[:,0]
v = z[:,1]

# plot the results

plt.plot(t,z[:,1])
plt.ylabel('velocity (m/s)')
plt.xlabel('time (s)')
#plt.legend(loc='best')
plt.show()

plt.plot(t,z[:,0])
plt.ylabel('position (m)')
plt.xlabel('time (s)')
#plt.legend(loc='best')
plt.show()





